### ISSUE TITLE
Numerical code block highlighting and preview issues

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1575]
@Waqar144, in the editor at `border:0px;` the number is highlighted differently if there is a space between the `:` and the number or not.

And in the preview the `#` is of `#898989` is missing.

![Screenshot 2020-01-12 at 08 13 48](https://user-images.githubusercontent.com/1798101/72215503-90e81100-3513-11ea-8d2a-3b8c1da37232.png)

```css
    .boton2 
    {
        background: #898989;
        border:0px;
        color:White;
        border-radius: 3px;
        padding: 6px 20px;
        font-size: 14px;
    }
    .boton2:focus 
    {
        outline:0px;
    }
    .boton2:hover 
    {
        background: #6E6E6E;   
    }
```

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `So. Jän. 12 17:26:39 2020`
**Version**: `20.1.7`
**Build date**: `Jan 12 2020`
**Build number**: `654`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.17`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
