### ISSUE TITLE
Highlighting in the editor cannot handle complex cases and has missing features

### ISSUE THREAD

**Issue by Waqar144** [pbek/QOwnNotes#1598]
- [x] Support for overlapping formats such as, bold+italic, code + italic, etc.
- [x] Em and strong highlighting falls apart quickly in complex cases
- [x] No strike through support
- [ ] No multiline headings support
- [ ] Link highlighting can have problems such as `[link](link.com).`, the last dot is getting highlighted

Example:
```
*italic* *italic*
*`code`*
```
might not get highlighted correctly

**Comment by pbek** [comment]
Most excellent!

**Comment by pbek** [comment]
@Waqar144, in 20.1.14 this code block is broken, it worked in 20.1.13:

    ```css
    a {color: green;}
    ~~~
    adas
    ~~~
    ```

**Comment by pbek** [comment]
These ones are ok:

    ~~~
    sdfs <strong>strong</strong>
    ~~~
    
    ~~~
    ```
    inner
    ```
    
    sdfs <strong>strong</strong>
    ~~~
    
    
    ~~~css
    a {color: green;}
    ~~~
    
    ```css
    a {color: green;}
    ```
