### ISSUE TITLE
oc integrity check on oc 9.0.3 failed - missing files

### ISSUE THREAD

**Issue by chriseqipe** [pbek/QOwnNotes#238]
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- Application to check
	- EXCEPTION
		- Exception
		- App not found
- qownnotesapi
	- FILE_MISSING
		- .gitignore
		- .travis.yml
		- Makefile
		- build/artifacts/appstore/qownnotesapi.tar.gz
		- phpunit.coverage.xml
		- phpunit.integration.xml
		- phpunit.xml
		- tests/integration/AppTest.php
		- tests/travis/php.ini
		- tests/unit/controller/NoteApiControllerTest.php

Raw output
==========
Array
(
    [Application to check] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => Exception
                    [message] => App not found
                )

        )

    [qownnotesapi] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.gitignore] => Array
                        (
                            [expected] => d5cc0283d4eb9d4adb7b11ef526d933fafc81e4a3c7191d2331ce6965170a7a1e7117aab69b730e4b25cf5354222230a72adb8a87fe60006929948217218537a
                            [current] => 
                        )

                    [.travis.yml] => Array
                        (
                            [expected] => e54c3c0cef4f1508b6d07fab2da159a136f2380cb62c5b93234b05dc20532e1b79a677b4287659833067d86c3d7f4fdfffdef2d5cd4cdfd9b9aa4520d9db9db5
                            [current] => 
                        )

                    [Makefile] => Array
                        (
                            [expected] => d2f61de81d762aaee5a5876798e702d513eb2ad80cd5e9a62ff256f4b88fb2f7da8876bd74ed7d20f2b95843d1de7c6eba155aaf1f9509029e3ec15b3256999a
                            [current] => 
                        )

                    [build/artifacts/appstore/qownnotesapi.tar.gz] => Array
                        (
                            [expected] => 609e55b65b3f683ebe4f2cfc3b36daf61e65105a7f839f8d049c8a77399defbed1d08bc549e06cb3139428d36c9fd5d6367a616a37fed016f7d80fb3be25d1eb
                            [current] => 
                        )

                    [phpunit.coverage.xml] => Array
                        (
                            [expected] => 21686e83eada96dd35b0187b5f9e5f4df15e9ab0faf36c54c8cc1f0631f739f56bbccb1a0668002ebb13104d7e28ecfec9b277ca665641b3abab4330a12dddca
                            [current] => 
                        )

                    [phpunit.integration.xml] => Array
                        (
                            [expected] => d477d2d4e122ea372352b7e3c96e6973ad6c82b04c3adeb1edf02029f1cff62240ac188b99e063c7423e7603098dd7ab89c8f146c5382d8c8a9e0a9117f70da3
                            [current] => 
                        )

                    [phpunit.xml] => Array
                        (
                            [expected] => c4b7fe8203adf562ae2aa01090b46d0a1337df7766285b97d5fe27be19636f5385deb08f19101305536423006deed50eb22f3cc7f6ebf5c1d2fc4fe009c961bc
                            [current] => 
                        )

                    [tests/integration/AppTest.php] => Array
                        (
                            [expected] => 6ab2b514e3abcdd947f10bdd53e548581bfdaf9cb13fc622860c23907cbeaa999ba472bb243c0812e98766ab8025c2447d5a2ddfaf4a7573483691b8a34ea478
                            [current] => 
                        )

                    [tests/travis/php.ini] => Array
                        (
                            [expected] => 42ae4f728eb4e0cec696ae48c61d58e50e836b0f291cf74fdc0d7229c565c2bf3c076ac150ce7250dde2e4600804f17404a09555e1978d7e79bb84d39e2c78e1
                            [current] => 
                        )

                    [tests/unit/controller/NoteApiControllerTest.php] => Array
                        (
                            [expected] => 08fba9788ace46accf2fb8e1a422294551782b093c8d0d6a87300172cf1b983e859f6786a1891a2ad6d5dc17fd008a674f43357e16f5126812ce261243110a46
                            [current] => 
                        )

                )

        )

)
```

**Comment by pbek** [comment]
How and where did you get that output?

**Comment by chriseqipe** [comment]
We have installed oc version 9.0.3.
```
php occ status
  - installed: true
  - version: 9.0.3.2
  - versionstring: 9.0.3
  - edition: 
```
on cli we got: 
```
php occ  integrity:check-app qownnotesapi
  - FILE_MISSING:
    - .gitignore:
      - expected: d5cc0283d4eb9d4adb7b11ef526d933fafc81e4a3c7191d2331ce6965170a7a1e7117aab69b730e4b25cf5354222230a72adb8a87fe60006929948217218537a
      - current: 
    - .travis.yml:
      - expected: e54c3c0cef4f1508b6d07fab2da159a136f2380cb62c5b93234b05dc20532e1b79a677b4287659833067d86c3d7f4fdfffdef2d5cd4cdfd9b9aa4520d9db9db5
      - current: 
    - Makefile:
      - expected: d2f61de81d762aaee5a5876798e702d513eb2ad80cd5e9a62ff256f4b88fb2f7da8876bd74ed7d20f2b95843d1de7c6eba155aaf1f9509029e3ec15b3256999a
      - current: 
    - build/artifacts/appstore/qownnotesapi.tar.gz:
      - expected: 609e55b65b3f683ebe4f2cfc3b36daf61e65105a7f839f8d049c8a77399defbed1d08bc549e06cb3139428d36c9fd5d6367a616a37fed016f7d80fb3be25d1eb
      - current: 
    - phpunit.coverage.xml:
      - expected: 21686e83eada96dd35b0187b5f9e5f4df15e9ab0faf36c54c8cc1f0631f739f56bbccb1a0668002ebb13104d7e28ecfec9b277ca665641b3abab4330a12dddca
      - current: 
    - phpunit.integration.xml:
      - expected: d477d2d4e122ea372352b7e3c96e6973ad6c82b04c3adeb1edf02029f1cff62240ac188b99e063c7423e7603098dd7ab89c8f146c5382d8c8a9e0a9117f70da3
      - current: 
    - phpunit.xml:
      - expected: c4b7fe8203adf562ae2aa01090b46d0a1337df7766285b97d5fe27be19636f5385deb08f19101305536423006deed50eb22f3cc7f6ebf5c1d2fc4fe009c961bc
      - current: 
    - tests/integration/AppTest.php:
      - expected: 6ab2b514e3abcdd947f10bdd53e548581bfdaf9cb13fc622860c23907cbeaa999ba472bb243c0812e98766ab8025c2447d5a2ddfaf4a7573483691b8a34ea478
      - current: 
    - tests/travis/php.ini:
      - expected: 42ae4f728eb4e0cec696ae48c61d58e50e836b0f291cf74fdc0d7229c565c2bf3c076ac150ce7250dde2e4600804f17404a09555e1978d7e79bb84d39e2c78e1
      - current: 
    - tests/unit/controller/NoteApiControllerTest.php:
      - expected: 08fba9788ace46accf2fb8e1a422294551782b093c8d0d6a87300172cf1b983e859f6786a1891a2ad6d5dc17fd008a674f43357e16f5126812ce261243110a46
      - current: 
```
app:list shows: 

```
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.2
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - qownnotesapi: true
  - systemtags: 0.2
  - templateeditor: 0.1
Disabled:
  - documents
  - encryption
  - files_antivirus
  - firstrunwizard
  - updatenotification
  - user_external
  - user_ldap
```
