### ISSUE TITLE
[website] problems regarding right-to-left direction

### ISSUE THREAD

**Issue by noureddin** [pbek/QOwnNotes#2382]
While I'm translating the website into Arabic, I'm frequently looking at the Persian website, as it's the only one currently deployed that is RTL.

### Code Blocks
I find that code blocks are not styled properly. Please check for example: https://www.qownnotes.org/fa/installation/raspberry-pi-os.html

All directions are mixed; it's neither aligned properly nor it's fully visible (the first few characters are always hidden under the number column, where the numbers themselves are positioned elsewhere).

I fixed all that by injecting the following CSS into the page:

```css
div.line-numbers-mode {
  /* fix the direction of the content in code blocks */
  direction: ltr;
  /* let the code not touch the right edge of the block */
  padding-right: 1rem;
}

div.line-numbers-wrapper {
  /* fix the placement of the line numbers */
  left: 0;
}
```

(This assumes all code block are LTR, which is generally true except in few places like in the [Markdown page](https://www.qownnotes.org/fa/getting-started/markdown.html), but the "best" solution I could arrive at is that such code blocks should be enclosed in `<div dir="rtl" align="right">` and `</div>` in the translation, which works fine, but only messes up the line-spacing or line-height, but that's only obvious if compared with the line numbers. I'm open for better suggestions.)

This same CSS should apply to all languages.

I also think the code blocks on the other languages sites need that `padding-right: 1rem`, too. 😅

### Inline Code

I think inline code should be `dir="ltr"` by default, and only overridden by the translator, if needed, by enclosing the translation in `<span dir="rtl">` and `</span>`.

### Navigation Links

The links for next and previous pages at the end of every page are not spaced properly. And the arrows are reversed.

I "fixed" that by injecting:

```css
.page-nav > .inner > .prev { float: right }
.page-nav > .inner > .next { float: left  }
.page-nav > .inner > .prev:before { content: '→' }
.page-nav > .inner > .next:after  { content: '←' }
```

But this is obviously assumes that the HTML no longer contains the arrows.

And this should only be applied only to RTL sites; LTR sites need them mirrored:

```css
.page-nav > .inner > .prev { float: left  }
.page-nav > .inner > .next { float: right }
.page-nav > .inner > .prev:before { content: '←' }
.page-nav > .inner > .next:after  { content: '→' }
```

### Lists

Lists, too, are not spaced properly. See for example:  <https://www.qownnotes.org/fa/getting-started/markdown.html#شکست-خط>.

I fixed them by injecting:

```css
ul, ol {
    padding-left: 0 !important;
    padding-right: 1.2em;
}
```

(I had to use `!important` on my end; I hope you don't need to.)

### Misc

- In the Markdown page, the formatting of the Tables section is messed up in many languages, like [German](https://www.qownnotes.org/de/getting-started/markdown.html#tabellen), [French](https://www.qownnotes.org/fr/getting-started/markdown.html#tableaux), and [Persian](https://www.qownnotes.org/fa/getting-started/markdown.html#%D8%AC%D8%AF%D8%A7%D9%88%D9%84).

- When I was inspecting the CSS, I found a number of `html:lang(fa)` selectors; isn't it better to have `dir="rtl"` on the html-tag (in addition to the `lang` attribute), and using the `html[dir="rtl"]` selector (or equivalent)? Using `dir="rtl"` on the html-tag is both [recommended and necessary](https://www.w3.org/International/questions/qa-html-dir#documentlevel). (Some languages can be written in different scripts with different directions.)
