### ISSUE TITLE
SearchLine direct stylesheet

### ISSUE THREAD

**Issue by Arty2** [pbek/QOwnNotes#2723]
The current implementation sets a stylesheet directly on the `` widget, which enforces high specificity and doesn't permit overrides.
Proposing to instead move those settings to the themes so that it can be easily styled, especially icon, borders etc.

e.g. in `mainwindow.ui` lines 107 and 294: https://github.com/pbek/QOwnNotes/blob/230c2b40dbe0f32edb3fbcd1a96dbd5ec6abcb24/src/mainwindow.ui#L107

```css
QLineEdit {
	border: none;
	padding: 2px 5px 2px 27px;
	background-image: url(:/images/search-notes.svg);
	background-repeat: no-repeat;
	background-position: center left;
	margin-right: 0px;
}
```

I am quite unfamiliar with QtStyles so there could be another way to override previous styles that I am unaware of. I am currently targeting using `QLineEdit#searchLineEdit { ... }`.
